### ISSUE TITLE
Hypnosspiralen hoppar ned på sidan

### ISSUE THREAD

**Issue by loveersare** [MattisLindmark/aps#1]
I passagen död då vi har hypnosspiralen i bakgrunden hoppar den nedåt då vi klickar fram texten. går det att ha den som en fast bakgrund som pendeln?

**Comment by MattisLindmark** [comment]
Ska va fixat nu. Testa. Och fundera över var den ska placeras. Den är ganska centrerad nu men flyttas lite beroende på stående och liggande format på tex mobil etc.
