### ISSUE TITLE
Ficklampan dyker inte upp i inventoryt

### ISSUE THREAD

**Issue by loveersare** [MattisLindmark/aps#2]
I städskrubvben, efter att ha letat igenom. Får pling och variabeln ändras men inget dyker upp i inventoryt trot att jag bytt passage

**Comment by loveersare** [comment]
Verkar ha löst sig!

**Comment by MattisLindmark** [comment]
Om inventory funkar som det ska i tex debugg, men inte i tex städskrubb så måste felet vara i det som står i twine-passagen i tex städskrubben.
